import { join } from "node:path";
import { mkdir, writeFile, rm } from "node:fs/promises";
import type { Route } from "./router";

export interface GeneratedEntry {
  route: Route;
  entryFile: string; // absolute path to the generated entry file
}

export async function generateEntry(
  route: Route,
  appRoot: string // where the developer's app lives — generated files go here
): Promise<GeneratedEntry> {

  const TEMP_DIR = join(appRoot, ".imhashem/generated");
  await mkdir(TEMP_DIR, { recursive: true });

  // normalize to forward slashes so import paths work on Windows too
  const pageClientFile = join(route.dir, "page.client.tsx").replace(/\\/g, "/");

  // this file is what actually gets bundled — the developer never sees it
  // it handles hydrateRoot, HMR state preservation, and StrictMode
  const content = `
// AUTO-GENERATED BY IMHASHEM — DO NOT EDIT
// This file is regenerated on every build.
// Edit page.client.tsx instead.

import { hydrateRoot } from "react-dom/client";
import { createElement, StrictMode } from "react";
import PageClient from "${pageClientFile}";

const elem = document.getElementById("__imhashem_client__")!;

hydrateRoot(elem, createElement(StrictMode, null, createElement(PageClient, null)));
`.trim();

  // name entry file after the route so multiple routes don't overwrite each other
  const routeName = route.urlPath === "/"
    ? "index"
    : route.urlPath.replace(/\//g, "-").replace(/:/g, "").replace(/^-/, "");

  const entryFile = join(TEMP_DIR, `${routeName}.entry.tsx`);
  await writeFile(entryFile, content);

  return { route, entryFile };
}

export async function cleanGeneratedEntries(
  isDev: boolean,
  appRoot: string
): Promise<void> {
  // keep generated files in dev for faster rebuilds, clean up in production
  if (isDev) return;
  await rm(join(appRoot, ".imhashem"), { recursive: true, force: true });
}
