import { join } from "node:path";
import { mkdir, writeFile, rm } from "node:fs/promises";
import type { Route } from "./router";

export interface GeneratedEntry {
  route: Route;
  // absolute path to the generated entry file
  entryFile: string;
}

export async function generateEntry(
  route: Route,
  hasLayout: boolean,
  layoutDir: string | null,
  // PROFESSIONAL: appRoot ensures generated files live inside the developer's
  // app directory, not the framework package. This guarantees node_modules
  // resolution works correctly since React is installed in the app, not the
  // framework. Simple alternative: generate inside the framework package —
  // breaks node_modules resolution in monorepos.
  appRoot: string
): Promise<GeneratedEntry> {

  const TEMP_DIR = join(appRoot, ".imhashem/generated");

  await mkdir(TEMP_DIR, { recursive: true });

  const pageClientFile = join(route.dir, "page.client.tsx")
    .replace(/\\/g, "/"); // normalize Windows paths to forward slashes for imports

  const layoutClientFile = hasLayout && layoutDir
    ? join(layoutDir, "layout.client.tsx").replace(/\\/g, "/")
    : null;

  // PROFESSIONAL: import.meta.hot preserves React state across hot reloads.
  // Simple alternative: always call createRoot() — works but loses all
  // React state (form inputs, open modals, counters etc) on every save.
  // This is exactly what the Bun React template does natively.
  const content = `
// AUTO-GENERATED BY IMHASHEM — DO NOT EDIT
// This file is regenerated on every build.
// Edit page.client.tsx or layout.client.tsx instead.

import { hydrateRoot, createRoot } from "react-dom/client";
import { createElement, StrictMode } from "react";
import PageClient from "${pageClientFile}";
${layoutClientFile ? `import LayoutClient from "${layoutClientFile}";` : ""}

const elem = document.getElementById("root")!;

// PROFESSIONAL: wrap in StrictMode to catch potential issues early.
// Simple alternative: no StrictMode — misses double-render checks
// and deprecated API warnings in development.
const app = createElement(
  StrictMode,
  null,
  ${layoutClientFile
    ? `createElement(LayoutClient, null, createElement(PageClient, null))`
    : `createElement(PageClient, null)`
  }
);

// PROFESSIONAL: import.meta.hot API for state-preserving HMR.
// When a file changes, React re-renders without losing state.
// Simple alternative: always createRoot() — full remount on every
// save, all state is lost.
if (import.meta.hot) {
  const root = (import.meta.hot.data.root ??= createRoot(elem));
  root.render(app);
} else {
  // production — no HMR, just mount once
  hydrateRoot(elem, app);
}
`.trim();

  // PROFESSIONAL: name entry file after the route to avoid collisions.
  // Simple alternative: always name it "entry.tsx" — routes overwrite each other.
  const routeName = route.urlPath === "/"
    ? "index"
    : route.urlPath.replace(/\//g, "-").replace(/:/g, "").replace(/^-/, "");

  const entryFile = join(TEMP_DIR, `${routeName}.entry.tsx`);
  await writeFile(entryFile, content);

  return { route, entryFile };
}

export async function cleanGeneratedEntries(
  isDev: boolean,
  appRoot: string
): Promise<void> {
  // PROFESSIONAL: in dev keep generated entries for faster HMR rebuilds.
  // In production clean up immediately — no leftover files in deployment.
  if (isDev) return;
  await rm(join(appRoot, ".imhashem"), { recursive: true, force: true });
}